##### This file can be used for Installing ISD,Argo CD and Argo Rollouts ###############################
# Update the controller URL which needs to be reachable from other clusters where ArgoCD is running
# After installation, the DNS must be updated to point this to EXTERNAL-IP of the agent-grpc service
# kubectl get svc -n opsmx-isd agent-grpc
forwarder:
  externalName: controller.REPLACE.THIS.WITH.YOURCOMPANY.COM  ## OPTIONAL, can be updated later, just leave it if trying for the 1st time

global:
  argocd:
    # Update the below string for all occurences in this file with proper dns entry to access the Argo CD UI eg: argocd.example.ops.com
    host: "ARGO.REPLACE.THIS.WITH.YOURCOMPANY.COM"

  argorollouts:
    # Update the below string with proper dns entry to access the Argo Rollouts UI eg: argorollouts.example.ops.com
    host: "ROLLOUTS.REPLACE.THIS.WITH.YOURCOMPANY.COM"

  oesUI:
    # Update the below string with proper dns entry to access the ISD UI eg: isdui.example.ops.com
    host: ISD.REPLACE.THIS.WITH.YOURCOMPANY.COM

  keycloak:
    # Update the below string with proper dns entry to access the keycloak UI eg: keycloak.example.ops.com
    host: KEYCLOAK.REPLACE.THIS.WITH.YOURCOMPANY.COM

  vela:
    # Update the below entry for establishing communication for ISD and Argo CD
    host: VELA.REPLACE.THIS.WITH.YOURCOMPANY.COM

###################################################
# argo-cd configuration
#######################
argo-cd:
  crds:
    install: true
  configs:
    cm:
      # Argo CD's externally facing base URL. Required when configuring SSO
      url: "https://ARGO.REPLACE.THIS.WITH.YOURCOMPANY.COM" ## Provide ArgoCD url like https://argocd.ninja-test.opsmx.net"
      # admin.enabled indicates whether the admin user is enabled. It is enabled by default.
      admin.enabled: "true"
      accounts.admin: apiKey
      configManagementPlugins: |-
        - name: argocd-vault-plugin
          generate:
            command: ["argocd-vault-plugin"]
            args: ["generate", "-s", "{{ .Release.Namespace }}:argocd-vault-plugin-credentials", "./"]
      dex.config: |-
        connectors:
        - type: ldap
          name: opsmx-openldap
          id: ldap
          config:
            host: "openldap:389"
            insecureNoSSL: true
            insecureSkipVerify: true
             # Variable name stores ldap bindDN in argocd-secret
            bindDN: "cn=admin,dc=example,dc=org"
            # Variable name stores ldap bind password in argocd-secret
            bindPW: "opsmxadmin123"
            usernamePrompt: Username
            # Ldap user serch attributes
            userSearch:
              baseDN: "dc=example,dc=org"
              filter: "(objectClass=simpleSecurityObject)"
              username: cn
              idAttr: cn
              emailAttr: cn
              nameAttr: cn
            # Ldap group serch attributes
            groupSearch:
              baseDN: "dc=example,dc=org"
              filter: "(objectClass=simpleSecurityObject)"
              userAttr: cn
              groupAttr: cn
              nameAttr: cn

    ################# groups and user permission in argcd-rbac-cm configmap configuration ################
    # -- Argo CD rbac config ([Argo CD RBAC policy])
    rbac:
      create: true
      # -- The name of the default role which Argo CD will falls back to, when authorizing API requests (optional).
      # If omitted or empty, users may be still be able to login, but will see no apps, projects, etc...
      #policy.csv |
      #  p, role:org-admin, applications, *, */*, allow
      #  p, role:org-admin, clusters, get, *, allow
      #  p, role:org-admin, repositories, *, *, allow
      #  p, role:org-admin, logs, get, *, allow
      #  p, role:org-admin, exec, create, */*, allow
      #  g, your-github-org:your-team, role:org-admin
      # -- OIDC scopes to examine during rbac enforcement (in addition to `sub` scope).
      # The scope value can be a string, or a list of strings.
      # -- OIDC scopes to examine during rbac enforcement (in addition to `sub` scope).
      # The scope value can be a string, or a list of strings.
      scopes: "[groups]"

  notifications:
    enabled: true
    argocdUrl: "ARGO.REPLACE.THIS.WITH.YOURCOMPANY.COM"  # Provide ArgoCd Url like argocd.ninja-test.opsmx.net

###################################################
# argo-rollouts configuration
#######################
argo-rollouts:
  # Default set to true . Set to false if crds already exists in the cluster instead of deleting the CRDs
  installCRDs: true
