{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: vela
{{ include "oes.standard-labels" . | indent 4 }}
  name: vela
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: vela
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oes
        component: vela
{{ include "oes.standard-labels" . | indent 8 }}
      annotations:
        checksum/secret: {{ (.Files.Glob "config/vela/vela-api.yaml").AsConfig | sha256sum }}
{{- if .Values.vela.annotations -}}
        {{ toYaml .Values.vela.annotations | nindent 8 }}
{{- end }}
    spec:
      volumes:
      - name: vela-volume
        configMap:
          name: vela-config
          items:
            - key: vela-api.yaml
              path: vela-api.yaml
          defaultMode: 420
      containers:
      - image: {{ template "vela.image" . }}
        imagePullPolicy: IfNotPresent
        name: vela
        ports:
        - containerPort: 8092
          protocol: TCP
        volumeMounts:
          - name: vela-volume
            mountPath: /app/config/vela-api.yaml
            subPath: vela-api.yaml
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      terminationGracePeriodSeconds: 30
{{- end -}}
